#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldfish.Areas.Manager.Views.Manager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Goldfish;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Manager/Settings.cshtml")]
    public partial class Settings : System.Web.Mvc.WebViewPage<IList<Goldfish.Extend.IModule>>
    {
        public Settings()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"sub-navigation\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n\t\t<h2>Settings</h2>\r\n\t\t<p>Here you can change the settings for your site and a" +
"ll your modules.</p>\r\n\t\t<ul>\r\n\t\t\t<li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">General</a></li>\r\n\t\t\t<li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Blog</a></li>\r\n\t\t</ul>\r\n");

            
            #line 11 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
		
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
         if (Model.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<ul>\r\n");

            
            #line 13 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
			
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
             foreach (var module in Model) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 375), Tuple.Create("\"", 467)
            
            #line 14 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
, Tuple.Create(Tuple.Create("", 382), Tuple.Create<System.Object, System.Int32>(Url.Action("Settings", "Manager", new { module = module.ConfigType.Name.ToLower() })
            
            #line default
            #line hidden
, 382), false)
);

WriteLiteral(">");

            
            #line 14 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
                                                                                                               Write(module.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 15 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</ul>\r\n");

            
            #line 17 "..\..\Areas\Manager\Views\Manager\Settings.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
