#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldfish.Views.Pages.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Goldfish.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pages/Partial/Menu.cshtml")]
    public partial class Menu : System.Web.Mvc.WebViewPage<IEnumerable<Goldfish.Pages.PageNav>>
    {
        public Menu()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Pages\Partial\Menu.cshtml"
 if (Model.Count() > 0) {

            
            #line default
            #line hidden
WriteLiteral("<ul ");

            
            #line 4 "..\..\Views\Pages\Partial\Menu.cshtml"
Write(Model.First().Level == 1 ? "class=menu" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

            
            #line 5 "..\..\Views\Pages\Partial\Menu.cshtml"
	
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Pages\Partial\Menu.cshtml"
     foreach (var nav in Model) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<li>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 172), Tuple.Create("\"", 193)
            
            #line 7 "..\..\Views\Pages\Partial\Menu.cshtml"
, Tuple.Create(Tuple.Create("", 179), Tuple.Create<System.Object, System.Int32>(nav.Permalink
            
            #line default
            #line hidden
, 179), false)
);

WriteLiteral(">");

            
            #line 7 "..\..\Views\Pages\Partial\Menu.cshtml"
                                Write(nav.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("\t\t\t");

            
            #line 8 "..\..\Views\Pages\Partial\Menu.cshtml"
       Write(Html.Partial("Partial/Menu", nav.SubPages));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</li>\r\n");

            
            #line 10 "..\..\Views\Pages\Partial\Menu.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");

            
            #line 12 "..\..\Views\Pages\Partial\Menu.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
