#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldfish.Areas.Manager.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Goldfish;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>This is the layout</title>\r\n\r\n\t<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 176), Tuple.Create("\"", 231)
            
            #line 9 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 183), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/css/style.min.css")
            
            #line default
            #line hidden
, 183), false)
);

WriteLiteral(" />\r\n</head>\r\n<body>\r\n\t<nav");

WriteLiteral(" id=\"navigation\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n\t\t<ul");

WriteLiteral(" id=\"main-navigation\"");

WriteLiteral(">\r\n\t\t\t<li><a");

WriteLiteral(" target=\"preview\"");

WriteAttribute("href", Tuple.Create(" href=\"", 351), Tuple.Create("\"", 369)
            
            #line 14 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 358), Tuple.Create<System.Object, System.Int32>(Href("~/")
            
            #line default
            #line hidden
, 358), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"icon-eye\"");

WriteLiteral("></span>Preview</a></li>\r\n\t\t\t<li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-gauge\"");

WriteLiteral("></span>Dashboard</a></li>\r\n\t\t\t<li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-newspaper\"");

WriteLiteral("></span>Content</a></li>\r\n\t\t\t<li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 572), Tuple.Create("\"", 613)
            
            #line 17 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 579), Tuple.Create<System.Object, System.Int32>(Url.Action("Settings", "Manager")
            
            #line default
            #line hidden
, 579), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"icon-cog\"");

WriteLiteral("></span>Settings</a></li>\r\n\t\t\t<li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 673), Tuple.Create("\"", 712)
            
            #line 18 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 680), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Account")
            
            #line default
            #line hidden
, 680), false)
);

WriteLiteral("><span");

WriteLiteral(" class=\"icon-logout\"");

WriteLiteral("></span>Logout</a></li>\r\n\t\t</ul>\r\n\t</nav>\r\n    <div");

WriteLiteral(" id=\"main\"");

WriteLiteral("> \r\n");

WriteLiteral("\t");

            
            #line 22 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
