// <auto-generated />
namespace Goldfish.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class CreateIndexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateIndexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201401232003337_CreateIndexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
